import React, { useEffect } from "react";

export const Disclaimer = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <div className="max-w-4xl mx-auto p-6 space-y-6">
      <h1 className="text-3xl font-bold text-gray-900 mb-8">Disclaimer</h1>

      <div className="prose prose-lg max-w-none">
        <p className="text-gray-700 leading-relaxed">
          The information and insights provided through Social Commerce
          Accountants Ltd (“SCA”) and its software platform (SCAi) are for
          informational purposes only. While we take reasonable steps to ensure
          accuracy, the outputs, reports, and analytics generated by the
          platform:
        </p>

        <ul className="space-y-3 mt-6 mb-6">
          <li className="flex items-start">
            <span className="text-gray-600 mr-3">•</span>
            <span className="text-gray-700">
              Do not constitute legal, financial, accounting, or tax advice.
            </span>
          </li>
          <li className="flex items-start">
            <span className="text-gray-600 mr-3">•</span>
            <span className="text-gray-700">
              Should not be relied upon as a substitute for professional
              judgment.
            </span>
          </li>
          <li className="flex items-start">
            <span className="text-gray-600 mr-3">•</span>
            <span className="text-gray-700">
              May be affected by limitations of third-party APIs, data
              availability, or user inputs.
            </span>
          </li>
        </ul>

        <p className="text-gray-700 leading-relaxed">
          SCA makes no warranties or guarantees, express or implied, regarding
          the accuracy, completeness, or reliability of any data presented
          through the Services. You remain solely responsible for reviewing your
          financial information, complying with applicable laws, and making
          business or tax decisions.
        </p>

        <p className="text-gray-700 leading-relaxed">
          To the fullest extent permitted by law, SCA disclaims liability for
          any loss or damage arising from reliance on information generated by
          the Services.
        </p>

        <p className="text-gray-700 leading-relaxed font-medium">
          For professional accounting or tax advice, please consult a qualified
          adviser.
        </p>
      </div>
    </div>
  );
};
