export const END_POINT = {
  auth: {
    login: "/auth/signin",
    signup: "/auth/signup",
    forgotPassword: "/auth/forgot-password",
    setNewPassowrd: "/auth/reset-password",
    google: "/auth/google",
    googleCallback: "/auth/google/callback",
  },
  user: {
    profile: "/user",
    onboarding: "/user/onboarding",
    businessProfile: "/user/business-profile",
    support: "/user/support",
    subscription: "/billing/checkout",
    unsubscribe: "/billing/unsubscribe",
  },
  team: {
    invite: "/team/invite",
    invitations: "/team/invitations?status=PENDING",
    myInvitations: "/team/invitations/me",
    invitation: "/team/invitation",
    members: "/team/members",
    member: "/team/member",
    updateMemberRole: "/team/member",
    analytics: "/team/analytics",
    memberSubscription: "/billing/checkout-team-member",
  },
  chatbot: {
    ask: "/chatbot/ask",
    history: "/chatbot/history",
    deleteMessage: "/chatbot/message",
  },
  chat: {
    createGroup: "/chat/group",
    getGroups: "/chat/groups",
    getGroupById: "/chat/group",
    updateGroup: "/chat/group",
    deleteGroup: "/chat/group",
    getFirebaseToken: "/chat/token",
    addMember: "/chat/group",
    removeMember: "/chat/group",
    updateMemberRole: "/chat/group",
  },
} as const;
